### PR TITLE
Move main package to org.eclipse.wasp

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
Btw, PR #30 did the same thing.

**Comment by arjantijms** [comment]
@joakime okay, I'll close 30 then if everything has already been done now. The one thing left to do is moving the org.glassfish.jsp package. I'll do that next then.

**Comment by joakime** [comment]
Still a lot of jasper references in master that PR #30 took care of.

**Comment by arjantijms** [comment]
> my mistake, had a merge failure I didn't catch.

No worries, thanks for confirming!

**Pull request merged**
