### PR TITLE
Fix #38 JSPC compile fails on JDK11 without compilerSourceVM and compilerTargetVM options.

### LINKED ISSUE #38: JSPC compile fails on JDK11 without compilerSourceVM and compilerTargetVM options.
## Environment Details
* GlassFish Version (and build number): GlassFish 6.2.3
* JDK version: OpenJDK version 11.0.12
* OS: CentOS Linux release 7
* Database: none

----------

## Problem Description
JSPC compile fails on JDK11 without compilerSourceVM and compilerTargetVM options and print the following messages on the console.
```
> jspc -webapp work/test -compile
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
Source option 5 is no longer supported. Use 6 or later.

PWC6199: Generated servlet error:
Target option 1.5 is no longer supported. Use 1.6 or later.
```
In JDK 9 and later, compiling with Java version 5 now fails.    

## Steps to reproduce
1. prepare any jsp file.
2. execute `jspc -webapp <dir> -compile` on JDK11.

### PR DESCRIPTION
**Pull request by kaido207**
* Fixes #38.
* And related #28.

Signed-off-by: kaido207 <kaido.hiroki@fujitsu.com>

### CODE REVIEW

**Comment by joakime** [comment]
Skip all of the minimum jvm checks, they are wrong for Java 11+.  Best to just let javac fail.

Food for thought.

If you are on Java 11 runtime, which this version of wasp has set as a minimum support level, then you only have Java source/target of `6` (or `1.6`) as a minimum.
If you are on Java 17 runtime, which this version of wasp has to certify via the TCK on, then you only have Java source/target of `7` (or `1.7`) as a minimum.

I'd be more curious as to what would happen if we instead had NO predefined or hard-coded source/target defined.
Make it use the runtime source/target (just like javac does).
This doesn't mean remove support for defining source/target if the user wants to, but why hard code it in the first place?

**Comment by kaido207** [comment]
@joakime Completely agree with you. I'd changed my proposal.

**Comment by kaido207** [comment]
@joakime Is there anything else I can do?

**Comment by arjantijms** [comment]
It looks good to me, if @joakime doesn't reply we can merge it by lazy consensus.

**Comment by joakime** [comment]
I'm in a mental fog (covid).  Do what you want here.

**Comment by kaido207** [comment]
Are there any other suggestions to merge this patch?

**Comment by kaido207** [comment]
@arjantijms Sure, I done.

**Comment by arjantijms** [comment]
@kaido207 thanks!

**Pull request merged**
