### PR TITLE
Issue #29 - move from Jasper to Wasp

### PR DESCRIPTION
**Pull request by joakime**
+ package rename of org.apache.jasper
  to org.eclipse.wasp
+ Class renames:
  + JasperException -> WaspException
  + JasperLoader -> WaspLoader
  + JasperTagInfo -> WaspTagInfo
+ Resource keys with jasper renamed
+ Property file values with "jasper" renamed
+ Documentation (including apidoc) references to "jasper" renamed
+ Build related functions with "jasper" renamed

### CODE REVIEW

**Comment by joakime** [comment]
@markt-asf the process to use a different package than `org.apache.jasper` has been started here.

**Comment by joakime** [comment]
@arjantijms there still exists a few `org.glassfish.jsp.api` interfaces here.

See: https://github.com/eclipse-ee4j/wasp/tree/master/src/main/java/org/glassfish/jsp/api

In light of the Jakarta EE 10 effort to use JPMS better, this alternate package in this JAR should be moved somewhere else.
But that can happen in a different PR.

**Comment by markt-asf** [comment]
With my ASF hat on, the change of package names is much appreciated.

**Comment by arjantijms** [comment]
Moving away from Jasper is perfect, I think we may even had that in the original plan, bu many of the other projects, including newer ones, use `org.glassfish.something`, although I think at least one newer project used `org.eclipse.something`.

Given the many other projects at Eclipse, I personally find `org.eclipse.[project name]` a wee bit too general, but that may just be me.

Thoughts?

**Comment by arjantijms** [comment]
Done in #34 now.

**Pull request closed without merging**
